name: Mouse and other peripherals support request
description: Request support for a new device
body:
  - type: input
    id: device
    attributes:
      label: Mouse / peripheral model and version
      placeholder: e.g. HP OMEN or HyperX peripheral model
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Vendor App Screenshots
      description: Connect your device to its official vendor app and upload screenshots of all relevant settings pages.
      placeholder: Drag and drop screenshots here
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: USB Details
      description: Also, please use <a href=https://www.uwe-sieber.de/usbtreeview.html>USB Tree View</a> and send the text, especially the block with all child devices.
      placeholder: USB Tree View details
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional information. 
      placeholder: If applicable, add screenshots or other relevant information          
